name: Run tests
on: 
  push_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with: 
          node-version: 16.13.x
          cach: yarn
      - name: Install dependencies
        run: |  
          yarn cache clean 
          yarn instal --network-concurrency 1
      - name: Running tests
        run: yarn test

